[Browser]
name = chrome

[AI]
default_ai = gemini
default_model_gemini = gemini-3.0-pro

[Cookies]
gemini_cookie_1psid = g.a0004gi02WpY00V5zQ-fbEAi9sgrhR9rFh6q5sonaVFGgHhrFngE1oNOVW2uvK8nIg9ywA6ZBQACgYKAQUSARISFQHGX2MiZgGVCidlKE6bCjW1wVpNjhoVAUF8yKp4zvZF43P6bPu5FymA1ZZq0076
gemini_cookie_1psidts = sidts-CjEBflaCdYdR5gy-EP_1u60XeYC8Rz8PuxOpmo8XbRCHo4w5xQEgToJclNuX4TJeiXJaEAA

[EnabledAI]
gemini = true

[Proxy]
http_proxy = 

